In [25]:
import cv2


pic = 'test_picture.jpg'
image = cv2.imread(pic)
# Получаем значение конкретного пикселя на изображении
px = image[100, 100]
print(px)

# Изменим значение конкретного пикселя
image[100, 100] = [255, 255, 255]
print(image[100, 100])

[206 118  42]
[255 255 255]


In [26]:
# Получаем доступ к красному каналу для конкретного пикселя на изображении
image.item(10, 10, 2)

28

In [27]:
# Изменяем значение для красного канала
image.itemset((10, 10, 2), 100)
image.item(10, 10, 2)

100

In [28]:
# Получаем размер изображения
print(image.shape)

# Общее количество пикселей на изображении
print(image.size)

# Тип данных изображения
print(image.dtype)

(2160, 3840, 3)
24883200
uint8


In [29]:
# Выбор и копирование региона изображения
img = image[280:340, 330:390]
image[273:333, 100:160] = img

cv2.imshow('image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
# Разделение на каналы
b, g, r = cv2.split(image)
# Изменение порядка каналов для другого пространства
image2 = cv2.merge((r, g, b))

cv2.imshow('image', image)
cv2.imshow('image2', image2)

# Другой вариант разделения и вывода изображения в зеленых тонах
image2[:,:,2] = 0
image2[:,:,0] = 0

bb = image2[:, :, 0]
gg = image2[:, :, 1]
rr = image2[:, :, 2]

image3 = cv2.merge((rr, gg, bb))

cv2.imshow('image3', image3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
import numpy as np


# Сложение двух изображений с использованием opencv и numpy
x, y = np.uint8([250]), np.uint8([10])
print(cv2.add(x, y))
print(x + y)

# Пример на реальных изображениях
image4 = cv2.add(image, image, image)
cv2.imshow('image4', image4)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[260.]
 [  0.]
 [  0.]
 [  0.]]
[4]


In [36]:
image = cv2.imread(pic)
logo = cv2.imread("logo.png",1)

# Создаем ROI
rows, cols, channels = logo.shape
roi = image[0:rows, 0:cols]

# Создаем маску логотипа и его инверсную маску
img2gray = cv2.cvtColor(logo, cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)

mask_inv = cv2.bitwise_not(mask)

# Затемняем область логотипа в ROI
img1_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)

# Берем только область логотипа из изображения логотипа.
img2_fg = cv2.bitwise_and(logo,logo,mask = mask)

# Помещаем логотип в ROI и изменяем основное изображение
dst = cv2.add(img1_bg,img2_fg)
image[0:rows, 0:cols] = dst

cv2.imshow('result', image)
cv2.imshow('inv', mask_inv)
cv2.imshow('bg', img1_bg)
cv2.imshow('fg', img2_fg)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
img1 = cv2.imread(pic)
logo.resize(2160, 3840, 3)
# Смешивание изображений с эффектом прозрачности
dst = cv2.addWeighted(img1, 0.7, logo, 0.3, 0)

cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()